# Generated by Django 2.0.5 on 2018-08-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display in the page.')),
                ('body', models.TextField(blank=True, help_text='HTML tags required!')),
                ('html_id', models.CharField(help_text='REQUIRED for accordions. No spaces and case-sensitive!', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.CharField(blank=True, help_text='Text to show on hover and if image fails', max_length=200, null=True)),
                ('caption', models.CharField(blank=True, help_text='Public description/figcaption to go below image. Optional!', max_length=400, null=True)),
                ('accordion_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AccordionCard')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('order', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('subheading', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, help_text='HTML tags required!')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Page')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Section'),
        ),
        migrations.AddField(
            model_name='accordioncard',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Page'),
        ),
    ]
