# Generated by Django 2.0.5 on 2018-05-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('season', models.CharField(default='2017/18', help_text='Format yyyy/yy', max_length=10)),
                ('role', models.CharField(max_length=100)),
                ('role_description', models.CharField(help_text='Description provided by personally by the committee member', max_length=1000)),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('project_term', models.CharField(help_text='e.g. Autumn, Winter, Spring, Summer 1, Summer 2', max_length=30)),
                ('start_time', models.TimeField(default='19:00:00', help_text='Start time of concert')),
                ('concert_date', models.DateField(verbose_name='concert date')),
                ('conductor_website', models.CharField(blank=True, max_length=300)),
                ('soloist', models.CharField(blank=True, max_length=100)),
                ('soloist_website', models.CharField(blank=True, max_length=200)),
                ('concert_venue', models.CharField(default="St. Stephen's Church, Gloucester Road, SW7 4RL", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConcertoApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('year', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), ('N/A', 'N/A')], max_length=1)),
                ('pieces', models.TextField()),
                ('years_ulso_member', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('second_round', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['instrument'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcertoWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('website', models.CharField(max_length=300)),
                ('biography', models.TextField()),
            ],
            options={
                'ordering': ['instrument'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('rate_per_rehearsal', models.IntegerField(default=125, help_text='Fee charged per 3 hour rehearsal.')),
                ('rate_concert_day', models.IntegerField(default=500, help_text='If only the price of the entire project was agreed, put zero per rehearsal and enter the entire fee here')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('member', models.BooleanField(default=False, help_text='Admitted to ULSO y/n')),
                ('season', models.CharField(blank=True, help_text='Academic year currently or last registered e.g. 2017/18', max_length=10)),
                ('year', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), ('N/A', 'N/A')], max_length=1)),
                ('experience', models.TextField(default='Briefly summarise your recent orchestral experience')),
                ('returning_member', models.BooleanField(default=False)),
                ('subs_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['instrument'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1_title', models.CharField(max_length=50)),
                ('main_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(help_text='Surname only', max_length=20)),
                ('piece', models.CharField(max_length=200)),
                ('order', models.IntegerField(blank=True, help_text='The order of the piece in the concert e.g. 1')),
                ('concert', models.ManyToManyField(to='ulsosite.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehearsal_date', models.DateTimeField(verbose_name='rehearsal date')),
                ('rehearsal_venue', models.CharField(max_length=300)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2_title', models.CharField(max_length=100)),
                ('section_description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_title', models.CharField(max_length=100)),
                ('sub_description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Section')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Conductor'),
        ),
    ]
