# Generated by Django 2.0.5 on 2018-05-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(default='2017/18', help_text='Format yyyy/yy', max_length=10)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('instrument', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=100)),
                ('role_description', models.CharField(help_text='Description provided by personally by the committee member', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('project_term', models.CharField(default='Enter a value', help_text='e.g. Autumn, Winter, Spring, Summer 1, Summer 2', max_length=30)),
                ('start_time', models.TimeField(help_text='Start time of concert')),
                ('concert_date', models.DateTimeField(verbose_name='concert date')),
                ('conductor', models.CharField(max_length=100)),
                ('conductor_website', models.CharField(blank=True, max_length=300)),
                ('soloist', models.CharField(blank=True, max_length=100)),
                ('soloist_website', models.CharField(blank=True, max_length=300)),
                ('concert_venue', models.CharField(default="St. Stephen's Church, Gloucester Road, SW7 4RL", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConcertoWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=300)),
                ('instrument', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1_title', models.CharField(max_length=50)),
                ('main_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(help_text='Surname only', max_length=20)),
                ('piece', models.CharField(max_length=200)),
                ('order', models.IntegerField(blank=True, help_text='The order of the piece in the concert e.g. 1')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehearsal_date', models.DateTimeField(verbose_name='rehearsal date')),
                ('rehearsal_venue', models.CharField(max_length=300)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2_title', models.CharField(max_length=100)),
                ('section_description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_title', models.CharField(max_length=100)),
                ('sub_description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Section')),
            ],
        ),
    ]
