# Generated by Django 2.0.5 on 2018-05-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('role_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('concert_date', models.DateTimeField(verbose_name='concert date')),
                ('conductor', models.CharField(max_length=100)),
                ('conductor_website', models.CharField(max_length=300)),
                ('soloist', models.CharField(default=None, max_length=100)),
                ('soloist_website', models.CharField(default=None, max_length=300)),
                ('concert_venue', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConcertoWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=300)),
                ('instrument', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(max_length=30)),
                ('piece', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehearsal_date', models.DateTimeField(verbose_name='rehearsal date')),
                ('rehearsal_venue', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=400)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Concert')),
            ],
        ),
    ]
