# Generated by Django 2.0.5 on 2018-08-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionslot',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ulsosite.AuditionDate'),
        ),
    ]
