# Generated by Django 2.0.5 on 2018-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Length in minutes'),
        ),
    ]
