# Generated by Django 2.0.5 on 2018-05-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='university',
            new_name='uni',
        ),
        migrations.RenameField(
            model_name='concertowinner',
            old_name='university',
            new_name='uni',
        ),
        migrations.AlterField(
            model_name='committee',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concert',
            name='concert_venue',
            field=models.CharField(default="St. Stephen's Church, Gloucester Road, SW7 4RL", max_length=300),
        ),
        migrations.AlterField(
            model_name='concert',
            name='conductor_website',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='concert',
            name='soloist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='concert',
            name='soloist_website',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='rehearsals',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
