# Generated by Django 2.0.5 on 2018-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='role_description',
            new_name='description',
        ),
    ]
