# Generated by Django 2.0.5 on 2018-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='concert',
            field=models.ManyToManyField(blank=True, to='ulsosite.Concert'),
        ),
    ]
