# Generated by Django 2.0.5 on 2018-06-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='main_description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_title',
            new_name='title',
        ),
    ]
