# Generated by Django 2.0.5 on 2018-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(verbose_name='concert date'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='project_term',
            field=models.CharField(help_text='e.g. Autumn, Winter, Spring, Summer 1, Summer 2', max_length=30),
        ),
        migrations.AlterField(
            model_name='concert',
            name='start_time',
            field=models.TimeField(default='19:00:00', help_text='Start time of concert'),
        ),
    ]
