# Generated by Django 2.0.5 on 2018-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulcontact',
            name='notes',
            field=models.TextField(blank=True, help_text='Insert fee structures here, e.g. £30 per poster', null=True),
        ),
    ]
