# Generated by Django 2.0.5 on 2018-07-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0002_auto_20180730_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
    ]
