# Generated by Django 2.0.5 on 2018-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0002_auto_20180516_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='conductor_website',
        ),
        migrations.AddField(
            model_name='piece',
            name='notes',
            field=models.CharField(blank=True, help_text='Give any particular details e.g. "needs 3 contrabassoons"', max_length=200),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(blank=True, help_text='This field is not required to facilitate quick fill-in. However, it is highly advised for you fill this in ASAP.', max_length=100),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
