# Generated by Django 2.0.5 on 2018-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0002_auto_20180518_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='harps',
            field=models.IntegerField(default=0, help_text='Number of harps'),
        ),
    ]
