# Generated by Django 2.0.5 on 2018-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0002_auto_20180510_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
