# Generated by Django 2.0.5 on 2018-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0002_auto_20180605_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertoauditionround',
            name='audition_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
