# Generated by Django 2.0.5 on 2018-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0003_concert_current'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committee',
            new_name='CommitteeMember',
        ),
        migrations.RenameModel(
            old_name='Rehearsals',
            new_name='Rehearsal',
        ),
    ]
