# Generated by Django 2.0.5 on 2018-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0003_auto_20180516_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='rehearsal_venue',
            field=models.CharField(default="St. Stephen's Church, Gloucester Road, SW7 4RL", max_length=300),
        ),
    ]
