# Generated by Django 2.0.5 on 2018-07-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0003_concert_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('artist', models.CharField(help_text='name of the artist', max_length=30)),
                ('website', models.CharField(blank=True, help_text="Artist's website, if exists", max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='poster',
        ),
        migrations.AddField(
            model_name='poster',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulsosite.Concert'),
        ),
    ]
