# Generated by Django 2.0.5 on 2018-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0004_auto_20180511_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='season',
            field=models.CharField(default='2017/18', help_text='Format yyyy/yy', max_length=10),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='role_description',
            field=models.CharField(help_text='Description provided by personally by the committee member', max_length=500),
        ),
    ]
