# Generated by Django 2.0.5 on 2018-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0004_auto_20180516_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='end_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='start_time',
            field=models.TimeField(default='19:00:00'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='rehearsal_date',
            field=models.DateField(verbose_name='rehearsal date'),
        ),
    ]
