# Generated by Django 2.0.5 on 2018-05-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0005_auto_20180511_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='role_description',
            field=models.CharField(help_text='Description provided by personally by the committee member', max_length=1000),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.CharField(help_text='Surname only', max_length=20),
        ),
        migrations.AlterField(
            model_name='piece',
            name='order',
            field=models.IntegerField(blank=True, help_text='The order of the piece in the concert e.g. 1'),
        ),
    ]
