# Generated by Django 2.0.5 on 2018-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0005_auto_20180516_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='main_description',
            field=models.TextField(blank=True),
        ),
    ]
