# Generated by Django 2.0.5 on 2018-06-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0005_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, help_text='You can choose to give the account a different name from the default', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Matched', 'Matched'), ('Equipment', 'Equipment'), ('Facilities', 'Facilities'), ('Self-Raised Funds', 'Self-Raised Funds'), ('Cashbox', 'Cashbox')], help_text='Student Central grants reset every year.', max_length=10),
        ),
    ]
