# Generated by Django 2.0.5 on 2018-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0006_auto_20180516_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_description',
            field=models.TextField(blank=True),
        ),
    ]
