# Generated by Django 2.0.5 on 2018-06-05 13:53

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0006_auto_20180605_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='notes',
            field=models.CharField(blank=True, help_text='e.g. describe the uses                              for this account', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='GBP', help_text='How much did we get from SC at                                the start of the academic year?', max_digits=5, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
