# Generated by Django 2.0.5 on 2018-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0007_auto_20180605_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='start_balance_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Out £'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter positive number', max_digits=5, null=True, verbose_name='In £'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much did we get from SC at                                the start of the academic year?', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(help_text='What was this transaction for?', max_length=50),
        ),
    ]
