# Generated by Django 2.0.5 on 2018-05-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0007_auto_20180516_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitteeMember',
        ),
        migrations.DeleteModel(
            name='ConcertoApplicant',
        ),
        migrations.DeleteModel(
            name='ConcertoWinner',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.AlterField(
            model_name='concert',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulso_admin.Conductor'),
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
    ]
