# Generated by Django 2.0.5 on 2018-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0008_auto_20180605_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_to',
            field=models.CharField(blank=True, help_text='Leave blank if money was received', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_from',
            field=models.CharField(blank=True, help_text='Leave blank if money was given away', max_length=30, null=True),
        ),
    ]
