# Generated by Django 2.0.5 on 2018-05-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0008_auto_20180517_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='conductor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ulso_admin.Conductor'),
        ),
    ]
