# Generated by Django 2.0.5 on 2018-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0009_auto_20180605_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much did we get from SC at                                the start of the academic year?', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Out £'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_to',
            field=models.CharField(blank=True, help_text='Leave blank if money was received', max_length=30, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_from',
            field=models.CharField(blank=True, help_text='Leave blank if money was given away', max_length=30, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdraw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter positive number', max_digits=10, null=True, verbose_name='In £'),
        ),
    ]
