# Generated by Django 2.0.5 on 2018-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulsosite', '0012_auto_20180605_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid_to',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='received_from',
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_to_or_from',
            field=models.CharField(blank=True, help_text='Leave blank if money was received', max_length=30, null=True, verbose_name='Paid to/Received from'),
        ),
    ]
