# Generated by Django 2.0.5 on 2018-05-26 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audition_date', models.CharField(blank=True, choices=[('Sat 23 Sep', 'Sat 23 Sep'), ('Sun 24 Sep', 'Sun 24 Sep'), ('Sat 30 Sep', 'Sat 30 Sep'), ('Sun 1 Oct', 'Sun 1 Oct'), ('Sat 7 Oct', 'Sat 7 Oct'), ('Sun 8 Oct', 'Sun 8 Oct')], max_length=30, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='0XXXX XXXXXX', max_length=30)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=20)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('season', models.CharField(default='2017/18', help_text='Format yyyy/yy', max_length=10)),
                ('role_description', models.TextField(help_text='Introduce yourself and tell people a bit about your role in ULSO.', max_length=1000)),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcertoApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='0XXXX XXXXXX', max_length=30)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=20)),
                ('pieces', models.TextField()),
                ('years_ulso_member', models.CharField(help_text='e.g. 2015-2017', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('second_round', models.BooleanField(default=False, help_text='Admitted to 2nd round')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('no_shortlist', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConcertoAuditionRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audition_date', models.CharField(blank=True, choices=[('Thur 15 Mar', 'Thur 15 Mar'), ('Thur 31 Mar', 'Thur 31 Mar')], max_length=30, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulso_admin.ConcertoApplicant')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertoWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='0XXXX XXXXXX', max_length=30)),
                ('website', models.URLField()),
                ('biography', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('rate_per_rehearsal', models.IntegerField(default=125, help_text='Fee charged per 3 hour rehearsal.')),
                ('rate_concert_day', models.IntegerField(default=500, help_text='If only the price of the entire project was agreed, put zero per rehearsal and enter the entire fee here')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='0XXXX XXXXXX', max_length=30)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=20)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=50)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('status', models.CharField(choices=[('Candidate', 'Candidate'), ('Member', 'Member'), ('Reserve', 'Reserve'), ('Contact', 'Contact List'), ('Rejected', 'Rejected'), ('Other', 'Other')], default='Candidate', max_length=30)),
                ('year', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), ('N/A', 'N/A')], max_length=5)),
                ('experience', models.TextField(default='Briefly summarise your recent orchestral experience')),
                ('returning_member', models.BooleanField(default=False)),
                ('subs_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['instrument'],
            },
            managers=[
                ('members', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='auditionslot',
            name='musician',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulso_admin.Musician'),
        ),
    ]
