# Generated by Django 2.0.5 on 2018-05-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('rate_per_hour', models.IntegerField()),
                ('rate_concert_day', models.IntegerField()),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date entered')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('Timpani & Percussion', 'Timpani & Percussion'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Other', 'Other university'), ('Graduate', 'Graduate')], max_length=1)),
                ('other_uni', models.CharField(default=None, max_length=50)),
                ('returning_member', models.BooleanField(default=False)),
                ('subs_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
