# Generated by Django 2.0.5 on 2018-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('season', models.CharField(default='2017/18', help_text='Format yyyy/yy', max_length=10)),
                ('role', models.CharField(max_length=100)),
                ('role_description', models.CharField(help_text='Description provided by personally by the committee member', max_length=1000)),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcertoApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('year', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), ('N/A', 'N/A')], max_length=1)),
                ('pieces', models.TextField()),
                ('years_ulso_member', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('second_round', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['instrument'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcertoWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('website', models.CharField(max_length=300)),
                ('biography', models.TextField()),
            ],
            options={
                'ordering': ['instrument'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, help_text='This field is not required to facilitate quick fill-in. However, it is highly advised for you fill this in ASAP.', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('rate_per_rehearsal', models.IntegerField(default=125, help_text='Fee charged per 3 hour rehearsal.')),
                ('rate_concert_day', models.IntegerField(default=500, help_text='If only the price of the entire project was agreed, put zero per rehearsal and enter the entire fee here')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, default=None, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('instrument', models.CharField(choices=[('Flute', 'Flute'), ('Clarinet', 'Clarinet'), ('Oboe', 'Oboe'), ('Bassoon', 'Bassoon'), ('Horn', 'Horn'), ('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Tuba', 'Tuba'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Cello', 'Cello'), ('Bass', 'Bass'), ('TimpaniPercussion', 'Timpani & Percussion'), ('Timpani', 'Timpani only'), ('Percussion', 'Percussion only'), ('Harp', 'Harp')], max_length=1)),
                ('doubling', models.CharField(blank=True, default=None, max_length=50)),
                ('uni', models.CharField(choices=[('RCM', 'Royal College of Music'), ('RAM', 'Royal Academy of Music'), ('Trinity', 'Trinity Laban Conservatoire'), ('GSMD', 'Guildhall School of Music and Drama'), ('KCL', "King's College London"), ('UCL', 'University College London'), ('ICL', 'Imperial College London'), ('LSE', 'London School of Economics'), ('RVC', 'Royal Veterinary College'), ('SOAS', 'SOAS'), ('RH', 'Royal Holloway'), ('City', 'City, University of London'), ('Goldsmiths', 'Goldsmiths, University of London'), ('LSHTM', 'London School of Hygiene and Tropical Medicine'), ('BK', 'Birkbeck'), ('QMUL', 'Queen Mary University of London'), ('Graduate', 'Graduate'), ('Other', 'Other')], max_length=1)),
                ('other_uni', models.CharField(blank=True, default=None, max_length=50)),
                ('member', models.BooleanField(default=False, help_text='Admitted to ULSO y/n')),
                ('season', models.CharField(blank=True, help_text='Academic year currently or last registered e.g. 2017/18', max_length=10)),
                ('year', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), ('N/A', 'N/A')], max_length=1)),
                ('experience', models.TextField(default='Briefly summarise your recent orchestral experience')),
                ('returning_member', models.BooleanField(default=False)),
                ('subs_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['instrument'],
                'abstract': False,
            },
        ),
    ]
