# Generated by Django 2.0.5 on 2018-05-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulso_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='season',
        ),
    ]
