# Generated by Django 2.0.5 on 2018-05-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulso_admin', '0002_auto_20180518_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='status',
            field=models.CharField(choices=[('Candidate', 'Audition Candidate'), ('Member', 'Member'), ('Reserve', 'Reserve'), ('Dep', 'Depped only'), ('Contact', 'Contact List'), ('Rejected', 'Rejected')], default='...', max_length=30),
        ),
    ]
