# Generated by Django 2.0.5 on 2018-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulso_admin', '0005_auto_20180518_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='concertoapplicant',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='concertowinner',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='musician',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
    ]
