# Generated by Django 2.0.5 on 2018-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulso_admin', '0005_auto_20180518_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='share_details',
            field=models.BooleanField(default=False, help_text='Please check this box if you grant ULSO permission to pass your contact details to other London orchestras who approach us for recruitment. We will also occasionally advertise vacencies in other orchestras. In these cases, you may choose to contact the orchestra directly.', verbose_name='Allow your details to be passed to other London orchestras'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='concertoapplicant',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='concertowinner',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='musician',
            name='phone',
            field=models.CharField(default='0XXXX XXXXXX', max_length=30),
        ),
    ]
